name: Run Python Script Daily

on:
  schedule:
    - cron: '30 12 * * *'  # Runs daily at 12:30 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: windows-latest  # Use Windows-based runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python

      # Step 3: Upgrade pip to the latest version
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Step 4: Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 5: Run the Python script (generate PNG file)
      - name: Run Python script
        run: python daily_accum_map.py  # This script should generate the PNG file

      # Step 6: Commit and push the generated PNG file
      - name: Commit and push PNG file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add daily_file/*.png
          git commit -m "Add daily snowfall PNG file" || echo "No changes to commit"
          git push
        continue-on-error: true  # Avoid failure if no new PNG is created

      - name: Set Environment Variables
        run: |
          echo "Setting Environment Variables..."
          echo "GOOGLE_EMAIL=${{ secrets.GOOGLE_EMAIL }}" >> $GITHUB_ENV
          echo "GOOGLE_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}" >> $GITHUB_ENV
          echo "EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}" >> $GITHUB_ENV
      - name: Debug Secrets
        run: |
          echo "Checking Secrets..."
            if [ -z "${{ secrets.GOOGLE_EMAIL }}" ]; then echo "❌ GOOGLE_EMAIL is MISSING"; else echo "✅ GOOGLE_EMAIL is SET"; fi
            if [ -z "${{ secrets.GOOGLE_APP_PASSWORD }}" ]; then echo "❌ GOOGLE_APP_PASSWORD is MISSING"; else echo "✅ GOOGLE_APP_PASSWORD is SET"; fi
            if [ -z "${{ secrets.EMAIL_RECIPIENTS }}" ]; then echo "❌ EMAIL_RECIPIENTS is MISSING"; else echo "✅ EMAIL_RECIPIENTS is SET"; fi

      # Step 8: Send Email with PNG Attachment
      - name: Send Email with PNG Attachment
        run: |
          python send_email.py
