name: Run Python Script Daily

on:
  schedule:
    - cron: '00 13 * * *'  # Runs daily at 12:30 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: windows-latest  # Use Windows-based runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run Report script
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python morning_weather_report.py

      - name: Run Email script
        env:
          GMAIL_PW: ${{ secrets.GMAIL_PW }}
        run: | 
          python send_email.py
