name: Run Python Script Daily

on:
  schedule:
    - cron: '30 12 * * *'  # Runs daily at 12:30 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: windows-latest  # Use Windows-based runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug Cache Key
      - name: Debug Cache Key
        run: echo "Cache Key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}"

      # Step 3: Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\pip\Cache  # Windows path for pip cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ runner.python.version }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python morning_weather_report.py
