name: Run Python Script Daily

on:
  schedule:
    - cron: '30 12 * * *'  # Runs daily at 12:30 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install system dependencies (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Or list individual packages like `numpy`, `geopandas`, etc.

      - name: Run Python script with secrets
        env:
          GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python daily_accum_map.py
