name: Run Python Script Daily

on:
  schedule:
    - cron: '30 12 * * *'  # Runs daily at 12:30 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: windows-latest  # You can switch to 'windows-latest' if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv  # Create a virtual environment in the 'venv' folder
          venv\Scripts\activate
      
      - name: Upgrade pip
        run: |
          venv/bin/activate  # Activate the virtual environment
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install the required packages

      - name: Run Python script with secrets
        env:
          GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python daily_accum_map.py
