name: Run Python Script Daily

on:
  schedule:
    - cron: '30 12 * * *'  # Runs daily at 12:30 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: windows-latest  # Use Windows-based runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python

      # Step 3: Cache dependencies to speed up installs
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip  # Linux/macOS
            C:\Users\runneradmin\AppData\Local\pip\Cache  # Windows
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      # Step 4: Install dependencies (only if not cached)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run Python script
      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python daily_accum_mapping.py
